[tool.poetry]
name = "koinput"
version = "0.2.0a3"
description = "Maximum simplification of Input / Output for text programs."
authors = ["Николай Перминов <kolya-perminov@ya.ru>"]

[tool.poetry.dependencies]
python = "^3.6"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
